# https://stackoverflow.com/questions/51729836/error-response-from-daemon-cannot-stop-container-signaling-init-process-cause
# https://github.com/mfvanek/useful-sql-scripts/blob/master/running_pg_in_docker/6.%20UI%20via%20pgAdmin/docker-compose.yml
version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "scraperdb"
      POSTGRES_USER: "scraperuser"
      POSTGRES_PASSWORD: "scraperpassword"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - scraperdb-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U scraperuser -d scraperdb"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    # restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    restart: unless-stopped
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@google.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False" # To allow running in desktop mode
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  scraperdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge