import numpy as np

mobile_mapping = {
            'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
            "Производитель": "manufacturer",
            "Дата выхода": "release_date",
            "Тип устройства": "device_type",
            "Вид устройства": "device_category",
            "Платформа": "platform",
            "Версия ОС": "os_version",
            "Серия": "series",
            "Стандарт связи": "network_standard",
            "Количество SIM-карт": "num_sim_cards",
            "Тип SIM-карты": "sim_type",
            "Диагональ экрана, \"": "screen_diagonal_inch",
            "Разрешение экрана, точек": "screen_resolution_px",
            "Технология экрана": "screen_technology",
            "Частота обновления экрана": "refresh_rate_hz",
            "Оперативная память": "ram_gb",
            "Встроенная память": "internal_storage_gb",
            "Поддержка карт памяти": "memory_card_support",
            "Камера": "camera",
            "Количество основных камер": "num_main_cameras",
            "Разрешение основной камеры, Мп": "main_camera_resolution_mp",
            "Максимальное разрешение видео": "max_video_resolution",
            "Количество кадров в секунду": "fps",
            "Беспроводная зарядка": "wireless_charging",
            "Быстрая зарядка": "fast_charging",
            "Обратная беспроводная зарядка": "reverse_wireless_charging",
            "Модули камеры": "camera_modules",
            "Конструкция корпуса": "body_construction",
            "Материал корпуса": "body_material",
            "Цвет корпуса": "body_color",
            "Ударопрочный корпус": "shockproof_body",
            "Пыле- и влагозащита": "dust_water_resistance",
            "Степень защиты (IP)": "ip_rating",
            "Высота, см": "height_cm",
            "Ширина, см": "width_cm",
            "Толщина, см": "thickness_cm",
            "Вес, г": "weight_g",
            "Число пикселей на дюйм, ppi": "ppi",
            "Соотношение сторон": "aspect_ratio",
            "Сенсорный экран": "touch_screen",
            "Защита от царапин": "scratch_protection",
            "Постоянная работа экрана": "always_on_display",
            "Производитель процессора": "processor_manufacturer",
            "Процессор": "processor",
            "Количество ядер процессора": "num_processor_cores",
            "Техпроцесс": "process_technology",
            "Диафрагма": "aperture",
            "Вспышка": "flash",
            "Автофокус": "autofocus",
            "Оптическая стабилизация": "optical_stabilization",
            "Оптический зум": "optical_zoom",
            "Макс. количество кадров в секунду": "max_fps",
            "Количество фронтальных камер": "num_front_cameras",
            "Разрешение фронтальной камеры, Мп": "front_camera_resolution_mp",
            "Диафрагма фронтальной камеры": "front_camera_aperture",
            "Вспышка фронтальной камеры": "front_camera_flash",
            "Автофокус фронтальной камеры": "front_camera_autofocus",
            "Разрешение видео фронтальной камеры": "front_camera_video_resolution",
            "Стереодинамики": "stereo_speakers",
            "Безопасность": "security_features",
            "Навигация": "navigation",
            "Беспроводные интерфейсы": "wireless_interfaces",
            "Разъемы": "ports",
            "Емкость аккумулятора, мАч": "battery_capacity_mah",
            "Аккумулятор": "battery",
            "Время воспроизведения видео, ч": "video_playback_time_h",
            "Время воспроизведения аудио, ч": "audio_playback_time_h",
            "Комплект поставки": "package_contents"
        }

washing_machine_mapping = {
     'name': 'name',
     'product_url': 'product_url',
     'offer_count': 'offer_count',
     'min_price': 'min_price',
     'Производитель': 'brand',
     'Тип загрузки': 'load_type',
     'Максимальная загрузка белья, кг': 'max_load',
     'Глубина, см': 'depth',
     'Ширина, см': 'width',
     'Высота, см': 'height',
     'Вес, кг': 'weight',
     'Количество программ': 'programs_number',
     'Дисплей': 'has_display',
     'Установка': 'installation_type',
     'Цвет': 'color',
     'Класс стирки': 'washing_class',
     'Дополнительное полоскание': 'additional_rinsing',
     'Максимальное количество оборотов отжима, об/мин': 'max_rpm',
     'Класс отжима': 'spinning_class',
     'Выбор скорости отжима': 'spinning_speed_selection',
     'Сушка': 'drying',
     'Класс энергопотребления': 'energy_class',
     'Дополнительные функции': 'addition_features',
     'Возможность дозагрузки белья': 'can_add_clothes',
     'Отмена отжима': 'cancel_spinning',
     'Программа «легкая глажка»': 'light_ironing',
     'Прямой привод (direct drive)': 'direct_drive',
     'Инверторный двигатель': 'inverter_motor',
     'Безопасность': 'safety_features',
     'Расход воды за стирку, л': 'water_consumption'
}

fridge_mapping = {
            'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
            "Производитель": "manufacturer",
            "Количество камер": "number_of_chambers",
            "Тип": "type",
            "Компоновка": "layout",
            "No Frost": "no_frost",
            "Зона свежести (BioFresh)": "biofresh_zone",
            "Цвет корпуса": "body_color",
            "Климатический класс": "climate_class",
            "Возможность перенавешивания дверей": "door_reversibility",
            "Дополнительная комплектация холодильного отделения": "additional_fridge_features",
            "Ручки": "handles",
            "Класс энергопотребления": "energy_class",
            "Инверторный компрессор": "inverter_compressor",
            "Тип управления": "control_type",
            "Расположение блока управления": "control_panel_location",
            "Дисплей": "display",
            # numeric
            "Количество компрессоров": "number_of_compressors",
            "Объем холодильной камеры, л": "fridge_volume_l",
            "Объем морозильной камеры, л": "freezer_volume_l",
            "Количество отделений морозильной камеры": "number_of_freezer_compartments",
            "Мощность замораживания, кг/сутки": "freezing_capacity_kg_per_day",
            "Высота, см": "height_cm",
            "Ширина, см": "width_cm",
            "Глубина, см": "depth_cm"
        }

tv_mapping = {
            'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
            "Производитель": "manufacturer",
            "Дата выхода": "release_date",
            "Тип": "type",
            "Диагональ экрана, \"": "screen_diagonal_inch",
            "Разрешение экрана": "screen_resolution",
            "Частота матрицы, Гц": "refresh_rate_hz",
            "Изогнутый экран": "curved_screen",
            "Поддержка 3D": "support_3d",
            "Smart TV": "smart_tv",
            "Платформа Smart TV": "smart_tv_platform",
            "Версия системы": "system_version",
            "Безрамочный дизайн": "frameless_design",
            "Цвет корпуса": "body_color",
            "Цвет рамки": "frame_color",
            "Цвет подставки": "stand_color",
            "Подставка": "stand",
            "Крепление на стену": "wall_mount",
            "Глубина цвета": "color_depth",
            "Расширенный динамический диапазон (HDR)": "hdr",
            "Форматы HDR": "hdr_formats",
            "Игровые функции": "gaming_features",
            "Процессор": "processor",
            "Фоновая подсветка": "backlight",
            "Голосовое управление": "voice_control",
            "ТВ-тюнер": "tv_tuner",
            "Сабвуфер": "subwoofer",
            "Звуковая панель (саундбар)": "soundbar",
            "Мощность звуковой системы, Вт": "sound_system_power_w",
            "Количество динамиков": "num_speakers",
            "Поддержка аудиокодеков объемного звука": "surround_sound_codec_support",
            "Поддержка HDMI eARC": "hdmi_earc_support",
            "Беспроводные интерфейсы": "wireless_interfaces",
            "Версия Bluetooth": "bluetooth_version",
            "Стандарт Wi-Fi": "wifi_standard",
            "Разъемы": "ports",
            "Кол-во разъемов HDMI": "num_hdmi_ports",
            "Версия HDMI": "hdmi_version",
            "Кол-во разъемов USB": "num_usb_ports",
            "Smart-пульт": "smart_remote",
            "Настенное крепление": "wall_mounting",
            "Крепление VESA": "vesa_mount",
            "Ширина, см": "width_cm",
            "Высота (с подставкой), см": "height_with_stand_cm",
            "Глубина (с подставкой), см": "depth_with_stand_cm",
            "Высота (без подставки), см": "height_without_stand_cm",
            "Толщина панели, см": "panel_thickness_cm",
            "Вес (с подставкой), кг": "weight_with_stand_kg",
            "Вес (без подставки), кг": "weight_without_stand_kg"
        }

kettle_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Тип": "Type",
    "Объем, л": "Capacity_L",  # 'л' stands for liters
    "Мощность, Вт": "Power_W",  # 'Вт' stands for watts
    "Тип нагревательного элемента": "Heating_Element_Type",
    "Материал корпуса": "Body_Material",
    "Дополнительные функции": "Additional_Features",
    "Подставка": "Base",
    "Особенности конструкции": "Design_Features"
}

vacuumcleaner_mapping = {
'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Тип": "Type",
    "Тип уборки": "Cleaning_Type",
    "Тип питания": "Power_Type",
    "Потребляемая мощность, Вт": "Power_Consumption_W",  # 'Вт' stands for watts
    "Регулятор мощности": "Power_Control",
    "Тип пылесборника": "Dust_Collector_Type",
    "Объем пылесборника, л": "Dust_Collector_Capacity_L",  # 'л' stands for liters
    "Тип трубки": "Tube_Type",
    "Материал трубки": "Tube_Material",
    "Дополнительно": "Additional_Features",
    "Ширина, см": "Width_cm",
    "Глубина, см": "Depth_cm",
    "Высота, см": "Height_cm",
    "Вес, кг": "Weight_kg"  # 'кг' stands for kilograms
}

headphones_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Дата выхода": "Release_Date",
    "Назначение": "Purpose",
    "Тип устройства": "Device_Type",
    "Вид": "Form_Factor",
    "Акустическое оформление": "Acoustic_Design",
    "Тип подключения": "Connection_Type",
    "Тип беспроводных наушников": "Wireless_Type",
    "Пыле- и влагозащита": "Dust_Water_Protection",
    "Степень защиты (IP)": "Protection_Rating_IP",
    "Материал корпуса": "Body_Material",
    "Цвет": "Color",
    "Количество наушников гарнитуры": "Number_of_Earbuds",
    "Крепление": "Mounting",
    "Объемное звучание": "Surround_Sound",
    "Автопауза": "Auto_Pause",
    "Активное шумоподавление": "Active_Noise_Cancellation",
    "Управление наушниками": "Headphone_Control",
    "Функции управления звуком": "Sound_Control_Functions",
    "Виды функций управления звуком": "Types_of_Sound_Control_Functions",
    "Регулировка громкости": "Volume_Control",
    "Конструкция микрофона": "Microphone_Design",
    "Тип излучателя": "Driver_Type",
    "Вес, г": "Weight_g",  # 'г' stands for grams
    "Шумоподавление микрофона": "Microphone_Noise_Cancellation",
    "Поддержка аудиокодеков Bluetooth": "Bluetooth_Audio_Codec_Support",
    "Тип беспроводного подключения": "Wireless_Connection_Type",
    "Версия Bluetooth": "Bluetooth_Version",
    "Макс. время работы от одного заряда, ч": "Max_Battery_Life_Per_Charge_h",  # 'ч' stands for hours
    "Время работы с зарядным кейсом, ч": "Battery_Life_With_Charging_Case_h",  # 'ч' stands for hours
    "Беспроводная зарядка": "Wireless_Charging",
    "Быстрая зарядка": "Fast_Charging",
    "Разъем для зарядки": "Charging_Port",
    "Комплект поставки": "Package_Contents"
}

smartwatch_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Дата выхода": "Release_Date",
    "Тип": "Type",
    "Подключение к смартфону": "Smartphone_Connection",
    "Технология экрана": "Screen_Technology",
    "Размер экрана, \"": "Screen_Size_inch",
    "Разрешение экрана": "Screen_Resolution",
    "Разрешающая способность экрана, ppi": "Screen_Density_ppi",
    "Яркость экрана": "Screen_Brightness",
    "Постоянная работа экрана": "Always_On_Display",
    "Размер корпуса": "Case_Size",
    "Процессор": "Processor",
    "Количество ядер процессора": "Processor_Cores",
    "Объем встроенной памяти": "Internal_Storage",
    "Встроенная камера": "Built_In_Camera",
    "Поддерживаемые операционные системы": "Supported_OS",
    "Операционная система": "Operating_System",
    "Управление часами": "Watch_Control",
    "Звонки": "Calls",
    "Поддержка SIM-карты": "SIM_Card_Support",
    "Материал корпуса": "Case_Material",
    "Цвет корпуса": "Case_Color",
    "Материал ремешка": "Strap_Material",
    "Тип застежки": "Clasp_Type",
    "Цвет ремешка": "Strap_Color",
    "Для кого": "For_Whom",
    "Серия": "Series",
    "Спортивные профили": "Sport_Profiles",
    "Виды спортивных профилей": "Types_of_Sport_Profiles",
    "Автораспознавание тренировок": "Auto_Workout_Detection",
    "Планировщик тренировок": "Workout_Planner",
    "Встроенный музыкальный плеер": "Built_In_Music_Player",
    "Магазин приложений": "App_Store",
    "Уведомления": "Notifications",
    "Голосовой помощник": "Voice_Assistant",
    "Дистанционное управление": "Remote_Control",
    "Оплата часами": "Watch_Payments",
    "Дополнительные функции": "Additional_Features",
    "Форма корпуса": "Case_Shape",
    "Пыле- и влагозащита": "Dust_Water_Protection",
    "Степень защиты (IP)": "Protection_Rating_IP",
    "Защита от царапин": "Scratch_Protection",
    "Вибрация": "Vibration",
    "Сменный браслет": "Replaceable_Strap",
    "Длина корпуса, мм": "Case_Length_mm",
    "Ширина корпуса, мм": "Case_Width_mm",
    "Толщина корпуса, мм": "Case_Thickness_mm",
    "Размеры ремешка": "Strap_Dimensions",
    "Размер ремешка": "Strap_Size",
    "Вес, г": "Weight_g",  # 'г' stands for grams
    "Ночной режим (второй FSTN экран)": "Night_Mode_Secondary_FSTN_Screen",
    "Датчики": "Sensors",
    "Навигация": "Navigation",
    "Беспроводные интерфейсы": "Wireless_Interfaces",
    "Версия Bluetooth": "Bluetooth_Version",
    "Емкость аккумулятора, мАч": "Battery_Capacity_mAh",  # 'мАч' stands for milliampere-hour
    "Макс. время работы в обычном режиме, ч": "Max_Battery_Life_Normal_h",  # 'ч' stands for hours
    "Макс. время работы, ч": "Max_Battery_Life_h",  # 'ч' stands for hours
    "Быстрая зарядка": "Fast_Charging",
    "Тип подзарядки": "Charging_Type",
    "Комплект поставки": "Package_Contents"
}

dishwasher_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Установка": "Installation",
    "Вместимость, комплектов": "Capacity_Sets",
    "Класс энергопотребления": "Energy_Class",
    "Класс мойки": "Washing_Class",
    "Класс сушки": "Drying_Class",
    "Тип сушки": "Drying_Type",
    "Тип управления": "Control_Type",
    "Инверторный двигатель": "Inverter_Motor",
    "Дисплей": "Display",
    "Уровень шума при работе, дБ": "Noise_Level_dB",  # 'дБ' stands for decibels
    "Цвет": "Color",
    "Энергопотребление за цикл, кВт⋅ч": "Energy_Consumption_Per_Cycle_kWh",  # 'кВт⋅ч' stands for kilowatt-hour
    "Расход воды за цикл, л": "Water_Consumption_Per_Cycle_L",  # 'л' stands for liters
    "Количество программ": "Number_of_Programs",
    "1/2 загрузки": "Half_Load",
    "Программа интенсивной мойки": "Intensive_Wash_Program",
    "Программа бережного мытья": "Delicate_Wash_Program",
    "Программа предварительного ополаскивания": "Pre_Rinse_Program",
    "Защита от протечек": "Leak_Protection",
    "Защита от детей": "Child_Lock",
    "Таймер отсрочки запуска": "Delay_Start_Timer",
    "Регулируемая по высоте корзина для посуды": "Adjustable_Height_Dish_Rack",
    "Ширина, см": "Width_cm",
    "Высота, см": "Height_cm",
    "Глубина, см": "Depth_cm",
    "Серия": "Series",
    "Спортивные профили": "Sport_Profiles",
    "Виды спортивных профилей": "Types_of_Sport_Profiles",
    "Автораспознавание тренировок": "Auto_Workout_Detection",
    "Планировщик тренировок": "Workout_Planner",
    "Встроенный музыкальный плеер": "Built_In_Music_Player",
    "Магазин приложений": "App_Store",
    "Уведомления": "Notifications",
    "Голосовой помощник": "Voice_Assistant",
    "Дистанционное управление": "Remote_Control",
    "Оплата часами": "Watch_Payments",
    "Дополнительные функции": "Additional_Features",
    "Форма корпуса": "Case_Shape",
    "Пыле- и влагозащита": "Dust_Water_Protection",
    "Степень защиты (IP)": "Protection_Rating_IP",
    "Защита от царапин": "Scratch_Protection",
    "Вибрация": "Vibration",
    "Сменный браслет": "Replaceable_Strap",
    "Длина корпуса, мм": "Case_Length_mm",
    "Ширина корпуса, мм": "Case_Width_mm",
    "Толщина корпуса, мм": "Case_Thickness_mm",
    "Размеры ремешка": "Strap_Dimensions",
    "Размер ремешка": "Strap_Size",
    "Вес, г": "Weight_g",  # 'г' stands for grams
    "Ночной режим (второй FSTN экран)": "Night_Mode_Secondary_FSTN_Screen",
    "Датчики": "Sensors",
    "Навигация": "Navigation",
    "Беспроводные интерфейсы": "Wireless_Interfaces",
    "Версия Bluetooth": "Bluetooth_Version",
    "Емкость аккумулятора, мАч": "Battery_Capacity_mAh",  # 'мАч' stands for milliampere-hour
    "Макс. время работы в обычном режиме, ч": "Max_Battery_Life_Normal_h",  # 'ч' stands for hours
    "Макс. время работы, ч": "Max_Battery_Life_h",  # 'ч' stands for hours
    "Быстрая зарядка": "Fast_Charging",
    "Тип подзарядки": "Charging_Type",
    "Комплект поставки": "Package_Contents"
}

hob_cooker_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Тип варочной панели": "Hob_Type",
    "Количество конфорок": "Number_of_Burners",
    "Материал поверхности": "Surface_Material",
    "Управление": "Control_Type",
    "Расположение органов управления": "Control_Location",
    "WOK-конфорка": "WOK_Burner",
    "Электроподжиг конфорок": "Burner_Electric_Ignition",
    "Решетки": "Grates",
    "Цвет": "Color",
    "Особенности": "Features",
    "Дисплей": "Display",
    "Ширина, см": "Width_cm",
    "Глубина, см": "Depth_cm",
    "Высота, см": "Height_cm",
    "Ширина встраивания, см": "Built_In_Width_cm",
    "Глубина встраивания, см": "Built_In_Depth_cm",
    "Программа бережного мытья": "Delicate_Wash_Program",  # Moved to the right category
    "Программа предварительного ополаскивания": "Pre_Rinse_Program",  # Moved to the right category
    "Защита от протечек": "Leak_Protection",  # Moved to the right category
    "Защита от детей": "Child_Lock",  # Moved to the right category
    "Таймер отсрочки запуска": "Delay_Start_Timer",  # Moved to the right category
    "Регулируемая по высоте корзина для посуды": "Adjustable_Height_Dish_Rack",  # Moved to the right category
    "Серия": "Series",  # Moved to the right category
    "Дополнительные функции": "Additional_Features",
}

oven_cooker_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Тип": "Type",
    "Объем, л": "Capacity_L",  # 'л' stands for liters
    "Мощность подключения, Вт": "Connected_Power_W",  # 'Вт' stands for watts
    "Функциональность": "Functionality",
    "Гриль": "Grill",
    "Оборудование": "Equipment",
    "Дверца духовки": "Oven_Door",
    "Количество стекол": "Number_of_Glasses",
    "Переключатели": "Switches",
    "Дисплей": "Display",
    "Таймер": "Timer",
    "Электроподжиг": "Electric_Ignition",
    "Высота ниши для встраивания, см": "Built_In_Height_cm",
    "Высота, см": "Height_cm",
    "Ширина ниши для встраивания, см": "Built_In_Width_cm",
    "Ширина, см": "Width_cm",
    "Глубина ниши для встраивания, см": "Built_In_Depth_cm",
    "Глубина, см": "Depth_cm",
}

iron_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "Manufacturer",
    "Тип утюга": "Iron_Type",
    "Материал подошвы": "Soleplate_Material",
    "Мощность, Вт": "Power_W",  # 'Вт' stands for watts
    "Регулировка подачи пара": "Steam_Adjustment",
    "Функции": "Functions",
    "Самоочистка": "Self_Cleaning",
    "Система защиты от накипи": "Anti_Scale_System",
    "Складная ручка": "Folding_Handle",
    "Сетевой кабель": "Power_Cord",
    "Дисплей": "Display",
    "Таймер": "Timer",
}

conditioner_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "manufacturer",
    "Тип": "type",
    "Тип внутреннего блока": "indoor_unit_type",
    "Режим обогрева": "heating_mode",
    "Дополнительные режимы": "additional_modes",
    "Количество внутренних блоков": "num_indoor_units",
    "Инверторное управление мощностью": "inverter_control",
    "Тип хладагента": "refrigerant_type",
    "Высота внешнего блока, см": "outdoor_height_cm",
    "Охлаждающая способность, BTU/ч": "cooling_capacity_btu",
    "Мощность охлаждения, кВт": "cooling_power_kw",
    "Мощность обогрева, кВт": "heating_power_kw",
    "Потребляемая мощность при охлаждении, кВт": "cooling_consumption_kw",
    "Расход воздуха макс., м3/ч": "max_airflow_m3h",
    "Уровень шума внутреннего блока (макс.), дБ": "indoor_noise_max_db",
    "Мин. темп-ра охлаждения, °С": "min_cooling_temp_c",
    "Макс. темп-ра охлаждения, °С": "max_cooling_temp_c",
    "Мин. темп-ра обогрева, °С": "min_heating_temp_c",
    "Макс. темп-ра обогрева, °С": "max_heating_temp_c",
    "Класс энергоэффективности": "energy_class",
    "Тип управления": "control_type",
    "Таймер": "timer",
    "Пульт ДУ": "remote_control",
    "Автоматический перезапуск": "auto_restart",
    "Режимы работы": "operating_modes",
    "Регулировка направления воздушного потока": "airflow_direction",
    "Регулировка скорости вентилятора": "fan_speed",
    "Фильтр от": "filter_type",
    "Cамоочистка": "self_cleaning",
    "Подсоединяемый воздуховод": "connectable_duct",
    "Высота внутр. блока сплит-системы/оконного/мобильного конд., см": "indoor_height_cm",
    "Ширина внутр. блока сплит-системы/оконного/мобильного конд., см": "indoor_width_cm",
    "Глубина внутр. блока сплит-системы/оконного/мобильного конд., см": "indoor_depth_cm",
    "Уведомления": "notifications",
    "Голосовой помощник": "voice_assistant",
    "Дистанционное управление": "remote_management",
    "Оплата часами": "payment_watch",
    "Дополнительные функции": "additional_features",
    "Форма корпуса": "body_shape",
    "Пыле- и влагозащита": "dust_moisture_protection",
    "Степень защиты (IP)": "protection_ip",
    "Защита от царапин": "scratch_protection",
    "Вибрация": "vibration",
    "Сменный браслет": "replaceable_strap",
    "Длина корпуса, мм": "body_length_mm",
    "Ширина корпуса, мм": "body_width_mm",
    "Толщина корпуса, мм": "body_thickness_mm",
    "Размеры ремешка": "strap_dimensions",
    "Размер ремешка": "strap_size",
    "Вес, г": "weight_g",
    "Ночной режим (второй FSTN экран)": "night_mode",
    "Датчики": "sensors",
    "Навигация": "navigation",
    "Беспроводные интерфейсы": "wireless_interfaces",
    "Версия Bluetooth": "bluetooth_version",
    "Емкость аккумулятора, мАч": "battery_capacity_mah",
    "Макс. время работы в обычном режиме, ч": "max_runtime_normal_h",
    "Макс. время работы, ч": "max_runtime_h",
    "Быстрая зарядка": "fast_charging",
    "Тип подзарядки": "charging_type",
    "Комплект поставки": "package_contents"
}

waterheater_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "manufacturer",
    "Тип": "type",
    "Способ нагрева": "heating_method",
    "Мощность, кВт": "power_kw",
    "Объем, л": "volume_l",
    "Напряжение сети": "voltage",
    "Тип бака": "tank_type",
    "Внутреннее покрытие бака": "tank_coating",
    "Смеситель": "mixer",
    "Подводка": "connection",
    "Установка": "installation",
    "Способ крепления": "mounting_method",
    "Управление": "control",
    "Дисплей": "display",
    "Глубина, см": "depth_cm",
    "Ширина, см": "width_cm",
    "Высота, см": "height_cm",
    "Вес, кг": "weight_kg"
}

microwave_mapping = {'name': 'name',
            'product_url': 'product_url',
            'offer_count': 'offer_count',
            'min_price': 'min_price',
    "Производитель": "manufacturer",
    "Тип": "type",
    "Способ нагрева": "heating_method",
    "Мощность, кВт": "power_kw",
    "Объем, л": "volume_l",
    "Напряжение сети": "voltage",
    "Тип бака": "tank_type",
    "Внутреннее покрытие бака": "interior_coating",
    "Смеситель": "mixer",
    "Подводка": "connection",
    "Установка": "installation",
    "Способ крепления": "mounting_method",
    "Управление": "control",
    "Дисплей": "display",
    "Глубина, см": "depth_cm",
    "Ширина, см": "width_cm",
    "Высота, см": "height_cm",
    "Вес, кг": "weight_kg"
}

if __name__ == '__main__':
    pass